/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-08-11 04:04:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"canonical\" href=\"https://www.daangn.com/\" />\r\n");
      out.write("<title>홍당무마켓 - 우리 동네 중고거래</title>\r\n");
      out.write("<link rel=\"author\" href=\"당근마켓\" />\r\n");
      out.write("<link href=\"/images/icons/shortcut_icon.png\" rel=\"shortcut icon\"\r\n");
      out.write("\ttype=\"image/x-icon\">\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\"\r\n");
      out.write("\thref=\"https://d1unjqcospf8gs.cloudfront.net/favicon.ico\" />\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\"\r\n");
      out.write("\thref=\"https://d1unjqcospf8gs.cloudfront.net/assets/home/base-5fd449a9ae8befbdeef7776030bd747ddb94c65231eec5a3144ba6d36c4cc815.css\" />\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://d1unjqcospf8gs.cloudfront.net/assets/home/base-4bad12c052c58f77c6e9f82182b7886ec85f0a617534048f6c793626f7031c4a.js\"></script>\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"192x192\"\r\n");
      out.write("\thref=\"/images/icons/daangn_logo_192.png\">\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header id=\"fixed-bar\">\r\n");
      out.write("  <div id=\"fixed-bar-wrap\">\r\n");
      out.write("    <h1 id=\"fixed-bar-logo-title\">\r\n");
      out.write("      <a href=\"/hongdangmu/main.jsp\">\r\n");
      out.write("        <span class=\"sr-only\">홍당무마켓</span>\r\n");
      out.write("        <img class=\"fixed-logo\" alt=\"홍당무마켓\" src=\"img/KakaoTalk_20190809_155307864.png\" />\r\n");
      out.write("</a>    </h1>\r\n");
      out.write("    \r\n");
      out.write("    <section id=\"fixed-bar-search\">\r\n");
      out.write("      <div class=\"search-input-wrap\">\r\n");
      out.write("        <span class=\"sr-only\">검색</span>\r\n");
      out.write("        <input type=\"text\" name=\"header-search-input\" id=\"header-search-input\" class=\"fixed-search-input\" placeholder=\"지역, 상품, 업체등을 검색해보세요.\" />\r\n");
      out.write("        <button id=\"header-search-button\">\r\n");
      out.write("          <img class=\"fixed-search-icon\" alt=\"Search\" src=\"https://d1unjqcospf8gs.cloudfront.net/assets/home/base/header/search-icon-db20a2e9e6b0fc922b44982d451cf1c967c86e8e8df270e71c300832a6f31f1a.svg\" />\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("    <section id=\"fixed-bar-download\">\r\n");
      out.write("      <h3 class=\"hide\">다운로드</h3>\r\n");
      out.write("      <a target=\"_blank\" class=\"fixed-download-button\" id=\"header-download-button-ios\" href=\"https://itunes.apple.com/kr/app/pangyojangteo/id1018769995?l=ko&amp;ls=1&amp;mt=8\">\r\n");
      out.write("        <img class=\"fixed-apple-store\" alt=\"App Store\" src=\"https://d1unjqcospf8gs.cloudfront.net/assets/home/base/header/apple-store-790f526e762ae58ec39274857ea3434959b7bd40fc23ec1f33a21983f3d024ff.svg\" />\r\n");
      out.write("        <div class=\"fixed-download-text\">App Store</div>\r\n");
      out.write("</a>      <a target=\"_blank\" class=\"fixed-download-button\" id=\"header-download-button-android\" href=\"https://play.google.com/store/apps/details?id=com.towneers.www\">\r\n");
      out.write("        <img class=\"fixed-google-play\" alt=\"Google Play\" src=\"https://d1unjqcospf8gs.cloudfront.net/assets/home/base/header/google-play-3c1802269ac6bedde598de4f2885286c18492748e5b58bd358254b26ee61e008.svg\" />\r\n");
      out.write("        <div class=\"fixed-download-text\">Google Play</div>\r\n");
      out.write("</a>    </section>\r\n");
      out.write("  </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section id=\"header-top\">\r\n");
      out.write("  <div id=\"header-title-wrap\">\r\n");
      out.write("    <h1 id=\"header-title\">\r\n");
      out.write("      우리 동네 중고 직거래 마켓\r\n");
      out.write("    </h1>\r\n");
      out.write("    <p id=\"header-title-desc\">\r\n");
      out.write("      동네 주민들과 가깝고 따뜻한 거래를 지금 경험해보세요.\r\n");
      out.write("    </p>\r\n");
      out.write("    <div id=\"header-image\"></div>\r\n");
      out.write("    <section id=\"top-keywords\">\r\n");
      out.write("      <h3 id=\"top-keywords-title\">\r\n");
      out.write("        <a id=\"top-keywords-link\" href=\"/top_keywords\">\r\n");
      out.write("            <span id=\"top-keywords-title-text\">오늘의 인기 검색어</span>\r\n");
      out.write("            <img class=\"right-arrow\" alt=\"오늘의 인기 검색어\" src=\"https://d1unjqcospf8gs.cloudfront.net/assets/home/base/icon-right-arrow-24a4ae5554b39aa379d82d49324861cf1be86129f3e540e302771ae84b89400b.svg\" />\r\n");
      out.write("</a>      </h3>\r\n");
      out.write("      <ul id=\"top-keywords-list\">\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"/search/%EC%9E%90%EC%A0%84%EA%B1%B0\">\r\n");
      out.write("                <p class=\"keyword-text\">자전거</p>\r\n");
      out.write("                <p class=\"rank\">\r\n");
      out.write("                        <span class=\"changed_rank\">-</span>\r\n");
      out.write("                </p>\r\n");
      out.write("</a>            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"/search/%EB%83%89%EC%9E%A5%EA%B3%A0\">\r\n");
      out.write("                <p class=\"keyword-text\">냉장고</p>\r\n");
      out.write("                <p class=\"rank\">\r\n");
      out.write("                      <span class=\"up\">▲</span>\r\n");
      out.write("                      <span class=\"changed_rank\">1</span>\r\n");
      out.write("                </p>\r\n");
      out.write("</a>            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"/search/%EC%97%90%EC%96%B4%EC%BB%A8\">\r\n");
      out.write("                <p class=\"keyword-text\">에어컨</p>\r\n");
      out.write("                <p class=\"rank\">\r\n");
      out.write("                      <span class=\"down\">▼</span>\r\n");
      out.write("                      <span class=\"changed_rank\">1</span>\r\n");
      out.write("                </p>\r\n");
      out.write("</a>            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"/search/%EC%87%BC%ED%8C%8C\">\r\n");
      out.write("                <p class=\"keyword-text\">쇼파</p>\r\n");
      out.write("                <p class=\"rank\">\r\n");
      out.write("                      <span class=\"up\">▲</span>\r\n");
      out.write("                      <span class=\"changed_rank\">1</span>\r\n");
      out.write("                </p>\r\n");
      out.write("</a>            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"/search/%EC%9D%98%EC%9E%90\">\r\n");
      out.write("                <p class=\"keyword-text\">의자</p>\r\n");
      out.write("                <p class=\"rank\">\r\n");
      out.write("                      <span class=\"down\">▼</span>\r\n");
      out.write("                      <span class=\"changed_rank\">1</span>\r\n");
      out.write("                </p>\r\n");
      out.write("</a>            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"/search/%EA%B0%80%EB%B0%A9\">\r\n");
      out.write("                <p class=\"keyword-text\">가방</p>\r\n");
      out.write("                <p class=\"rank\">\r\n");
      out.write("                      <span class=\"down\">▼</span>\r\n");
      out.write("                      <span class=\"changed_rank\">3</span>\r\n");
      out.write("                </p>\r\n");
      out.write("</a>            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"/search/%EC%8B%9C%EA%B3%84\">\r\n");
      out.write("                <p class=\"keyword-text\">시계</p>\r\n");
      out.write("                <p class=\"rank\">\r\n");
      out.write("                      <span class=\"up\">▲</span>\r\n");
      out.write("                      <span class=\"changed_rank\">1</span>\r\n");
      out.write("                </p>\r\n");
      out.write("</a>            </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </section>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section id=\"hot-articles\">\r\n");
      out.write(" <h3>홍당무마켓 인기 매물</h3>\r\n");
      out.write("  <div class=\"title-line-divider\"></div>\r\n");
      out.write("    <section class=\"cards-wrap\">\r\n");
      out.write("      <article class=\"card-top \">\r\n");
      out.write("  <a class=\"card-link \" data-event-label=\"36655534\" href=\"/articles/36655534\">\r\n");
      out.write("    <div class=\"card-photo\">\r\n");
      out.write("        <img alt=\"전자렌지\" src=\"https://dnvefa72aowie.cloudfront.net/origin/article/201908/0131e6c68cdd4f2b4f32358873436b6a88a3ae2c93b945d08e23f64135f44014.jpg?q=82&amp;s=300x300&amp;t=crop\" />\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card-desc\">\r\n");
      out.write("      <h2 class=\"card-title\">전자렌지</h2>\r\n");
      out.write("      <div class=\"card-region-name\">\r\n");
      out.write("        충남 천안시 동남구 청당동\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"card-price \">\r\n");
      out.write("        15,000원\r\n");
      out.write("      </div>\r\n");
      out.write("        <div class=\"card-counts\">\r\n");
      out.write("          <span>\r\n");
      out.write("            관심 5\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            댓글 1\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            채팅 32\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</a></article><article class=\"card-top \">\r\n");
      out.write("  <a class=\"card-link \" data-event-label=\"36637412\" href=\"/articles/36637412\">\r\n");
      out.write("    <div class=\"card-photo\">\r\n");
      out.write("        <img alt=\"이케아 편안한 독서의자 무료나눔\" src=\"https://dnvefa72aowie.cloudfront.net/origin/article/201908/060ED745AE42920F03B2E5645B3350FEBAF75CB79E0383280149E790F14FB7DD.jpg?q=82&amp;s=300x300&amp;t=crop\" />\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card-desc\">\r\n");
      out.write("      <h2 class=\"card-title\">이케아 편안한 독서의자 무료나눔</h2>\r\n");
      out.write("      <div class=\"card-region-name\">\r\n");
      out.write("        서울 노원구 상계5동\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"card-price \">\r\n");
      out.write("        무료나눔\r\n");
      out.write("      </div>\r\n");
      out.write("        <div class=\"card-counts\">\r\n");
      out.write("          <span>\r\n");
      out.write("            관심 12\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            댓글 0\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            채팅 29\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</a></article><article class=\"card-top \">\r\n");
      out.write("  <a class=\"card-link \" data-event-label=\"36653780\" href=\"/articles/36653780\">\r\n");
      out.write("    <div class=\"card-photo\">\r\n");
      out.write("        <img alt=\"자전거 팝니다\" src=\"https://dnvefa72aowie.cloudfront.net/origin/article/201908/3C37E33486B45C583223F7F7AAD9EFB5525E245E92A63E3E694C92CA613E4283.jpg?q=82&amp;s=300x300&amp;t=crop\" />\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card-desc\">\r\n");
      out.write("      <h2 class=\"card-title\">자전거 팝니다</h2>\r\n");
      out.write("      <div class=\"card-region-name\">\r\n");
      out.write("        서울 송파구 잠실6동\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"card-price \">\r\n");
      out.write("        50,000원\r\n");
      out.write("      </div>\r\n");
      out.write("        <div class=\"card-counts\">\r\n");
      out.write("          <span>\r\n");
      out.write("            관심 21\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            댓글 2\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            채팅 24\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</a></article><article class=\"card-top \">\r\n");
      out.write("  <a class=\"card-link \" data-event-label=\"36195544\" href=\"/articles/36195544\">\r\n");
      out.write("    <div class=\"card-photo\">\r\n");
      out.write("        <img alt=\"도시락용 종이 봉투\" src=\"https://dnvefa72aowie.cloudfront.net/origin/article/201908/7D0D08AD8C2EE2C43A028D50073420CE8D09B1EB6E56C2DD97972DFFBD377FD3.jpg?q=82&amp;s=300x300&amp;t=crop\" />\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card-desc\">\r\n");
      out.write("      <h2 class=\"card-title\">도시락용 종이 봉투</h2>\r\n");
      out.write("      <div class=\"card-region-name\">\r\n");
      out.write("        경기도 고양시 일산동구 정발산동\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"card-price \">\r\n");
      out.write("        무료나눔\r\n");
      out.write("      </div>\r\n");
      out.write("        <div class=\"card-counts\">\r\n");
      out.write("          <span>\r\n");
      out.write("            관심 47\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            댓글 9\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            채팅 102\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</a></article><article class=\"card-top \">\r\n");
      out.write("  <a class=\"card-link \" data-event-label=\"36660275\" href=\"/articles/36660275\">\r\n");
      out.write("    <div class=\"card-photo\">\r\n");
      out.write("        <img alt=\"엔틱책상\" src=\"https://dnvefa72aowie.cloudfront.net/origin/article/201908/33bfa11da10e9363912ad1f9d5c61426b837ed49f7882e3b9589e36ecc497f72.jpg?q=82&amp;s=300x300&amp;t=crop\" />\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card-desc\">\r\n");
      out.write("      <h2 class=\"card-title\">엔틱책상</h2>\r\n");
      out.write("      <div class=\"card-region-name\">\r\n");
      out.write("        경남 창원시 마산회원구 양덕2동\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"card-price blank-price\">\r\n");
      out.write("        -\r\n");
      out.write("      </div>\r\n");
      out.write("        <div class=\"card-counts\">\r\n");
      out.write("          <span>\r\n");
      out.write("            관심 5\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            댓글 0\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            채팅 18\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</a></article><article class=\"card-top \">\r\n");
      out.write("  <a class=\"card-link \" data-event-label=\"36600076\" href=\"/articles/36600076\">\r\n");
      out.write("    <div class=\"card-photo\">\r\n");
      out.write("        <img alt=\"TV 판매해요\" src=\"https://dnvefa72aowie.cloudfront.net/origin/article/201908/8a630612acb3ccde5821b00de15dda6c7f8f77c74a675be05bb34f44e7a5a734.jpg?q=82&amp;s=300x300&amp;t=crop\" />\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card-desc\">\r\n");
      out.write("      <h2 class=\"card-title\">TV 판매해요</h2>\r\n");
      out.write("      <div class=\"card-region-name\">\r\n");
      out.write("        강원도 원주시 원동\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"card-price blank-price\">\r\n");
      out.write("        -\r\n");
      out.write("      </div>\r\n");
      out.write("        <div class=\"card-counts\">\r\n");
      out.write("          <span>\r\n");
      out.write("            관심 10\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            댓글 0\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            채팅 30\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</a></article><article class=\"card-top \">\r\n");
      out.write("  <a class=\"card-link \" data-event-label=\"36648630\" href=\"/articles/36648630\">\r\n");
      out.write("    <div class=\"card-photo\">\r\n");
      out.write("        <img alt=\"전자피아노\" src=\"https://dnvefa72aowie.cloudfront.net/origin/article/201908/df3e21229fc1f356fde02aa036250def9b4cf9e5402c60e91094b09adc4693b7.jpg?q=82&amp;s=300x300&amp;t=crop\" />\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card-desc\">\r\n");
      out.write("      <h2 class=\"card-title\">전자피아노</h2>\r\n");
      out.write("      <div class=\"card-region-name\">\r\n");
      out.write("        전북 전주시 완산구 삼천동1가\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"card-price \">\r\n");
      out.write("        5,000원\r\n");
      out.write("      </div>\r\n");
      out.write("        <div class=\"card-counts\">\r\n");
      out.write("          <span>\r\n");
      out.write("            관심 15\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            댓글 0\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            채팅 17\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</a></article><article class=\"card-top \">\r\n");
      out.write("  <a class=\"card-link \" data-event-label=\"36501388\" href=\"/articles/36501388\">\r\n");
      out.write("    <div class=\"card-photo\">\r\n");
      out.write("        <img alt=\"전자렝지 화장대 서랍장 옷장2개 침대2인용 냉장고 접이식 수납겸 식탁 화장대 팝니다\" src=\"https://dnvefa72aowie.cloudfront.net/origin/article/201908/33F8D3FD379B4BE04ED30C18CE003F09B5AB34402E38B86E90FF11DF5C0C6602.jpg?q=82&amp;s=300x300&amp;t=crop\" />\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card-desc\">\r\n");
      out.write("      <h2 class=\"card-title\">전자렝지 화장대 서랍장 옷장2개 침대2인용 냉장고 접이식 수납겸 식탁 화장대 팝니다</h2>\r\n");
      out.write("      <div class=\"card-region-name\">\r\n");
      out.write("        충북 청주시 상당구 용암1동\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"card-price blank-price\">\r\n");
      out.write("        -\r\n");
      out.write("      </div>\r\n");
      out.write("        <div class=\"card-counts\">\r\n");
      out.write("          <span>\r\n");
      out.write("            관심 18\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            댓글 10\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            채팅 75\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</a></article>\r\n");
      out.write("    </section>\r\n");
      out.write("    <div id=\"hot-articles-nanum-wrap\">\r\n");
      out.write("      <section class=\"cards-wrap\">\r\n");
      out.write("        <article class=\"card-top \">\r\n");
      out.write("  <a class=\"card-link \" data-event-label=\"36658019\" href=\"/articles/36658019\">\r\n");
      out.write("    <div class=\"card-photo\">\r\n");
      out.write("        <img alt=\"협탁 무료나눔합니다.\" src=\"https://dnvefa72aowie.cloudfront.net/origin/article/201908/0cda7b57ad5feb42d7ae47aeafe61e04bd05993b6f1ed886c62cf36401d671fe.jpg?q=82&amp;s=300x300&amp;t=crop\" />\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card-desc\">\r\n");
      out.write("      <h2 class=\"card-title\">협탁 무료나눔합니다.</h2>\r\n");
      out.write("      <div class=\"card-region-name\">\r\n");
      out.write("        광주 광산구 신창동\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"card-price \">\r\n");
      out.write("        무료나눔\r\n");
      out.write("      </div>\r\n");
      out.write("        <div class=\"card-counts\">\r\n");
      out.write("          <span>\r\n");
      out.write("            관심 2\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            댓글 0\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            채팅 8\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</a></article><article class=\"card-top \">\r\n");
      out.write("  <a class=\"card-link \" data-event-label=\"36658051\" href=\"/articles/36658051\">\r\n");
      out.write("    <div class=\"card-photo\">\r\n");
      out.write("        <img alt=\"필요하신분\" src=\"https://dnvefa72aowie.cloudfront.net/origin/article/201908/5bfdf5b686c41ae10138ce419069d01537bf823459e038e37604db31363b1478.jpg?q=82&amp;s=300x300&amp;t=crop\" />\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card-desc\">\r\n");
      out.write("      <h2 class=\"card-title\">필요하신분</h2>\r\n");
      out.write("      <div class=\"card-region-name\">\r\n");
      out.write("        제주 제주시 외도동\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"card-price \">\r\n");
      out.write("        무료나눔\r\n");
      out.write("      </div>\r\n");
      out.write("        <div class=\"card-counts\">\r\n");
      out.write("          <span>\r\n");
      out.write("            관심 4\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            댓글 0\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            채팅 8\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</a></article><article class=\"card-top \">\r\n");
      out.write("  <a class=\"card-link \" data-event-label=\"36617013\" href=\"/articles/36617013\">\r\n");
      out.write("    <div class=\"card-photo\">\r\n");
      out.write("        <img alt=\"가구들\" src=\"https://dnvefa72aowie.cloudfront.net/origin/article/201908/e54cea070594939669f9be8e08b410d284da13544704df342a0e64d3d2616708.jpg?q=82&amp;s=300x300&amp;t=crop\" />\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card-desc\">\r\n");
      out.write("      <h2 class=\"card-title\">가구들</h2>\r\n");
      out.write("      <div class=\"card-region-name\">\r\n");
      out.write("        강원도 원주시 단계동\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"card-price \">\r\n");
      out.write("        무료나눔\r\n");
      out.write("      </div>\r\n");
      out.write("        <div class=\"card-counts\">\r\n");
      out.write("          <span>\r\n");
      out.write("            관심 4\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            댓글 0\r\n");
      out.write("          </span>\r\n");
      out.write("          ∙\r\n");
      out.write("          <span>\r\n");
      out.write("            채팅 14\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</a></article>\r\n");
      out.write("        <div class=\"card-top \" id=\"cards-more\">\r\n");
      out.write("  <a class=\"card-link\" href=\"/hot_articles\">\r\n");
      out.write("    <div id=\"cards-more-text\">\r\n");
      out.write("      <img alt=\"+\" src=\"https://d1unjqcospf8gs.cloudfront.net/assets/home/base/mobile/icon-add-dcfb7aac98f18d19ca4c27e9dc29c63cf73861f3b10e0a42c06163d2658d0691.svg\" />\r\n");
      out.write("      <div id=\"more-text\">홍당무마켓<br />인기 매물<br />더 보기</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</a></div>\r\n");
      out.write("\r\n");
      out.write("      </section>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section id=\"introduction\">\r\n");
      out.write("  <h3>홍당무마켓은 이런 점이 달라요!</h3>\r\n");
      out.write("  <div class=\"title-line-divider\"></div>\r\n");
      out.write("  <div id=\"introduction-wrap\">\r\n");
      out.write("    <section class=\"introduction-detail\">\r\n");
      out.write("      <div class=\"home-checkin\"></div>\r\n");
      out.write("      <h5 class=\"introduction-title\">동네 인증</h5>\r\n");
      out.write("      <p class=\"introduction-desc\">\r\n");
      out.write("        설정한 동네를 인증한<br/>\r\n");
      out.write("        주민만 거래할 수 있어요.\r\n");
      out.write("      </p>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"introduction-detail\">\r\n");
      out.write("      <div class=\"home-temperature\"></div>\r\n");
      out.write("      <h5 class=\"introduction-title\">거래 매너 온도</h5>\r\n");
      out.write("      <p class=\"introduction-desc\">\r\n");
      out.write("        거래하기 전, 프로필에 있는<br/>\r\n");
      out.write("        매너 온도를 확인해보세요.\r\n");
      out.write("      </p>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"introduction-detail\">\r\n");
      out.write("      <div class=\"home-chatting\"></div>\r\n");
      out.write("      <h5 class=\"introduction-title\">1:1 채팅하기</h5>\r\n");
      out.write("      <p class=\"introduction-desc\">\r\n");
      out.write("        거래할 상대방과 부담 없이<br />\r\n");
      out.write("        대화할 수 있어요.\r\n");
      out.write("      </p>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"introduction-detail\">\r\n");
      out.write("      <div class=\"home-notification\"></div>\r\n");
      out.write("      <h5 class=\"introduction-title\">가격 하락 알림</h5>\r\n");
      out.write("      <p class=\"introduction-desc\">\r\n");
      out.write("        관심 게시물의 가격이 떨어지면<br/>\r\n");
      out.write("        가격 하락 알림을 받을 수 있어요.\r\n");
      out.write("      </p>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"introduction-detail\">\r\n");
      out.write("      <div class=\"home-share\"></div>\r\n");
      out.write("      <h5 class=\"introduction-title\">나눔의 날</h5>\r\n");
      out.write("      <p class=\"introduction-desc\">\r\n");
      out.write("        매월 11일, 안쓰는 물건을 나누고<br/>\r\n");
      out.write("        이웃과 추억도 공유해보세요.\r\n");
      out.write("      </p>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"introduction-detail\">\r\n");
      out.write("      <div class=\"home-thanks\"></div>\r\n");
      out.write("      <h5 class=\"introduction-title\">감사 인사</h5>\r\n");
      out.write("      <p class=\"introduction-desc\">\r\n");
      out.write("        거래 후에는 서로에게<br />\r\n");
      out.write("        감사 인사를 보내보세요.\r\n");
      out.write("      </p>\r\n");
      out.write("    </section>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section id=\"reviews\">\r\n");
      out.write("  <h3>홍당무마켓 사용자 후기</h3>\r\n");
      out.write("  <div class=\"title-line-divider\"></div>\r\n");
      out.write("  <ul id=\"reviews-list\">\r\n");
      out.write("      <li class=\"review\">\r\n");
      out.write("        <div class=\"home-icon-quotation\"></div>\r\n");
      out.write("        <div class=\"reviews-text\">\r\n");
      out.write("          근처에 있는 사람들끼리 거래하니까 뭔가 더 믿을 수 있는 것 같아요. 동네에서 바로 직거래할 수 있는 물건만 볼 수 있어 좋은 것 같아요. \r\n");
      out.write("          <span class=\"review-region-name\"> - 서울 잠실3동</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"review\">\r\n");
      out.write("        <div class=\"home-icon-quotation\"></div>\r\n");
      out.write("        <div class=\"reviews-text\">\r\n");
      out.write("          여기는 모랄까 돈 버는 것이 목적이 아닌 이웃들과 안 쓰는 물건들을 공유하고 정을 주고받는 동네 장터 같아요. 거래할 때마다 이웃의 정을 느낄 수 있어 좋았답니다.\r\n");
      out.write("          <span class=\"review-region-name\"> - 울산 삼산동</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"review\">\r\n");
      out.write("        <div class=\"home-icon-quotation\"></div>\r\n");
      out.write("        <div class=\"reviews-text\">\r\n");
      out.write("          믿을 수 있고, 무엇보다 직거래할 수 있어서 편하네요! 좋은 물건들이 거래되다 보니 중독성도 은근 강함 ㅋㅋ 놓칠까 봐 자꾸 들여다보게 되네요.\r\n");
      out.write("          <span class=\"review-region-name\"> - 광명 철산3동</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"review\">\r\n");
      out.write("        <div class=\"home-icon-quotation\"></div>\r\n");
      out.write("        <div class=\"reviews-text\">\r\n");
      out.write("          동네에서 바로 직거래하니까 사기 걱정도 없고 좋네요 ^^ 동네 사람들이니까 신뢰도 가고 가끔 쿨매 나오면 좋아요 ~~\r\n");
      out.write("          <span class=\"review-region-name\"> - 분당 정자동</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"review\">\r\n");
      out.write("        <div class=\"home-icon-quotation\"></div>\r\n");
      out.write("        <div class=\"reviews-text\">\r\n");
      out.write("          집에 있는 안 쓰는 물건 팔기 좋아요 :) 동네 사람들이랑 직거래할 수 있어서 소소한 물건 팔기 좋아요!\r\n");
      out.write("          <span class=\"review-region-name\"> - 인천 주안1동</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"review\">\r\n");
      out.write("        <div class=\"home-icon-quotation\"></div>\r\n");
      out.write("        <div class=\"reviews-text\">\r\n");
      out.write("          요즘 미니멀라이프 실천 중인데 당근마켓만한 앱이 없어요! 미니멀리즘을 위한 앱이랄까요?ㅎㅎ 동네 직거래라 쉽고 간편해서 너무 좋아요^^ 중고거래에 빠져있답니다❤︎\r\n");
      out.write("          <span class=\"review-region-name\"> - 부산 부전제1동</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"review\">\r\n");
      out.write("        <div class=\"home-icon-quotation\"></div>\r\n");
      out.write("        <div class=\"reviews-text\">\r\n");
      out.write("          아나바다 운동하는 것 같아서 좋아요ㅎ 저한텐 필요 없는 물건이 필요한 사람에게 전달될 수 있는 공간을 열어주셔서 감사합니다! \r\n");
      out.write("          <span class=\"review-region-name\"> - 광주 관천동</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"review\">\r\n");
      out.write("        <div class=\"home-icon-quotation\"></div>\r\n");
      out.write("        <div class=\"reviews-text\">\r\n");
      out.write("          당근에서 거래하는 재미에 쏙 빠졌어요~ 안쓰는 물건 나눔하고 피드백 받는 경험도 너무 좋았어요~ 동네라서 정말 편해요. 넘나 애정하는 어플 응원할게요!\r\n");
      out.write("          <span class=\"review-region-name\"> - 대전 둔산2동</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"review\">\r\n");
      out.write("        <div class=\"home-icon-quotation\"></div>\r\n");
      out.write("        <div class=\"reviews-text\">\r\n");
      out.write("          요즘 매일 쓰는 벼룩 앱이에요:) 근처 주민이라 믿을만하고 쉽게 거래할 수 있어요~ 동네에서 올라오는 매물 구경하는 맛에 완전 중독됐어요!! 진짜 안써본 사람은 몰라요 ㅋㅋ\r\n");
      out.write("          <span class=\"review-region-name\"> - 제주 노형동</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<footer id=\"footer\">\r\n");
      out.write("  <ul class=\"footer-list\">\r\n");
      out.write("    <li class=\"footer-list-item\"><a target=\"_blank\" href=\"http://policy.daangn.com/terms.html\">이용약관</a></li>\r\n");
      out.write("    <li class=\"footer-list-item\"><a target=\"_blank\" href=\"http://policy.daangn.com/privacy.html\">개인정보 취급방침</a></li>\r\n");
      out.write("    <li class=\"footer-list-item\"><a target=\"_blank\" href=\"https://policy.daangn.com/location.html\">위치기반서비스 이용약관</a></li>\r\n");
      out.write("    <li class=\"footer-list-item text-bold\"><a target=\"_blank\" href=\"https://ad.daangn.com/\">광고주센터</a></li>\r\n");
      out.write("    <li class=\"footer-list-item\"><a target=\"_blank\" href=\"http://team.daangn.com\">ABOUT US</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("  <ul class=\"footer-list\" id=\"footer-address-list\">\r\n");
      out.write("    <li class=\"footer-list-item\">사업자 등록번호 : 000-00-00000</li>\r\n");
      out.write("    <li class=\"footer-list-item\"><address>서울특별시 서초구 서초대로77길 55 에이프로스퀘어 3층 </address></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("  <p id=\"ceo\">\r\n");
      out.write("    (주)홍당무마켓  대표 김세훈\r\n");
      out.write("  </p>\r\n");
      out.write("  <div id=\"copyright\">\r\n");
      out.write("    Copyright © hongdangmu Market Inc. All rights reserved.\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"social\">\r\n");
      out.write("    <ul class=\"footer-list\">\r\n");
      out.write("      <li class=\"footer-list-item\"><a target=\"_blank\" class=\"footer-facebook\" href=\"https://www.facebook.com/daangn\">facebook</a></li>\r\n");
      out.write("      <li class=\"footer-list-item\"><a target=\"_blank\" class=\"footer-instagram\" href=\"https://www.instagram.com/daangn.m/\">instagram</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
